export { NavBar } from "./NavBar";
export { MainCard } from "./MainCard";
export { WhatsAppPopUp } from "./WhatsAppPopUp";
export { Cards } from "./Cards";
export { CategoryCard } from "./CategoryCard";
export { Loading } from "./Loading"
export { Footer } from './Footer'
export { Slideshow } from './Slideshow'
export { BarraInformativa } from './BarraInformativa'